logging:
  level:
    hu.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

account:
  balance:
    default: 5000
cors-policies: https://kickstarter.progmasters.hu
frontend-url: https://kickstarter.progmasters.hu
