server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/angular_fundraiser?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: fundraiser.progmasters@gmail.com
    password: wykytjhfmpxfjkcs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: '*'

logging:
  level:
    hu.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

exchange-api-url: http://data.fixer.io/api/latest?access_key=ccbcdaedbc16e8cbc37bd02fb523823a&base=EUR&symbols=USD,HUF,GBP

cors-policies: http://localhost:4200
frontend-url: http://localhost:4200
captcha-url: https://www.google.com/recaptcha/api/siteverify
captcha-secret: 6LeIKWQaAAAAAH0ok5g2-wWn7U2AE69oHgz4lOOQ
